import type { userRoleEnum } from '$lib/server/db/schema';

export type UserRole = (typeof userRoleEnum.enumValues)[number];

export const PERMISSIONS = {
	TENANT_CREATE: 'tenant:create',
	TENANT_UPDATE: 'tenant:update',
	TENANT_DELETE: 'tenant:delete',
	TENANT_READ_ALL: 'tenant:read:all',

	ADMISSION_PATHS_READ: 'admission_paths:read',
	ADMISSION_PATHS_CREATE: 'admission_paths:create',
	ADMISSION_PATHS_UPDATE: 'admission_paths:update',
	ADMISSION_PATHS_DELETE: 'admission_paths:delete',
	ADMISSION_PATHS_PUBLISH: 'admission_paths:publish',
	ADMISSION_PATHS_CLOSE: 'admission_paths:close',
	ADMISSION_PATHS_ARCHIVE: 'admission_paths:archive',

	FEES_READ: 'fees:read',
	FEES_CREATE: 'fees:create',
	FEES_UPDATE: 'fees:update',
	FEES_DELETE: 'fees:delete',

	ADMIN_USERS_READ: 'admin_users:read',
	ADMIN_USERS_CREATE: 'admin_users:create',
	ADMIN_USERS_ASSIGN_ROLE: 'admin_users:assign_role',
	ADMIN_USERS_REVOKE_ACCESS: 'admin_users:revoke_access',

	APPLICATIONS_READ: 'applications:read',
	APPLICATIONS_VERIFY: 'applications:verify',
	APPLICATIONS_REJECT: 'applications:reject',

	SCORES_INPUT: 'scores:input',
	SCORES_UPDATE: 'scores:update',

	// Epic 4.2: Scoring & Interview Input
	SCORE_CREATE: 'score:create',
	SCORE_READ: 'score:read',
	SCORE_UPDATE: 'score:update',
	SCORE_FINALIZE: 'score:finalize',
	SCORE_UNLOCK: 'score:unlock',

	PAYMENTS_READ: 'payments:read',
	PAYMENTS_VERIFY_MANUAL: 'payments:verify_manual',
	PAYMENTS_MANAGE: 'payments:manage',

	REPORTS_READ: 'reports:read',
	REPORTS_EXPORT: 'reports:export'
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
	super_admin: [
		PERMISSIONS.TENANT_CREATE,
		PERMISSIONS.TENANT_UPDATE,
		PERMISSIONS.TENANT_DELETE,
		PERMISSIONS.TENANT_READ_ALL,
		PERMISSIONS.ADMISSION_PATHS_READ,
		PERMISSIONS.ADMISSION_PATHS_CREATE,
		PERMISSIONS.ADMISSION_PATHS_UPDATE,
		PERMISSIONS.ADMISSION_PATHS_DELETE,
		PERMISSIONS.ADMISSION_PATHS_PUBLISH,
		PERMISSIONS.ADMISSION_PATHS_CLOSE,
		PERMISSIONS.ADMISSION_PATHS_ARCHIVE,
		PERMISSIONS.FEES_READ,
		PERMISSIONS.FEES_CREATE,
		PERMISSIONS.FEES_UPDATE,
		PERMISSIONS.FEES_DELETE,
		PERMISSIONS.ADMIN_USERS_READ,
		PERMISSIONS.ADMIN_USERS_CREATE,
		PERMISSIONS.ADMIN_USERS_ASSIGN_ROLE,
		PERMISSIONS.ADMIN_USERS_REVOKE_ACCESS,
		PERMISSIONS.APPLICATIONS_READ,
		PERMISSIONS.APPLICATIONS_VERIFY,
		PERMISSIONS.APPLICATIONS_REJECT,
		PERMISSIONS.SCORES_INPUT,
		PERMISSIONS.SCORES_UPDATE,
		PERMISSIONS.PAYMENTS_READ,
		PERMISSIONS.PAYMENTS_VERIFY_MANUAL,
		PERMISSIONS.PAYMENTS_MANAGE,
		PERMISSIONS.REPORTS_READ,
		PERMISSIONS.REPORTS_EXPORT
	],

	school_admin: [
		PERMISSIONS.ADMISSION_PATHS_READ,
		PERMISSIONS.ADMISSION_PATHS_CREATE,
		PERMISSIONS.ADMISSION_PATHS_UPDATE,
		PERMISSIONS.ADMISSION_PATHS_DELETE,
		PERMISSIONS.ADMISSION_PATHS_PUBLISH,
		PERMISSIONS.ADMISSION_PATHS_CLOSE,
		PERMISSIONS.ADMISSION_PATHS_ARCHIVE,
		PERMISSIONS.FEES_READ,
		PERMISSIONS.FEES_CREATE,
		PERMISSIONS.FEES_UPDATE,
		PERMISSIONS.FEES_DELETE,
		PERMISSIONS.ADMIN_USERS_READ,
		PERMISSIONS.ADMIN_USERS_CREATE,
		PERMISSIONS.ADMIN_USERS_ASSIGN_ROLE,
		PERMISSIONS.ADMIN_USERS_REVOKE_ACCESS,
		PERMISSIONS.APPLICATIONS_READ,
		PERMISSIONS.APPLICATIONS_VERIFY,
		PERMISSIONS.APPLICATIONS_REJECT,
		PERMISSIONS.SCORES_INPUT,
		PERMISSIONS.SCORES_UPDATE,
		PERMISSIONS.SCORE_UNLOCK, // NEW: Epic 4.2 - Can unlock finalized scores
		PERMISSIONS.PAYMENTS_READ,
		PERMISSIONS.PAYMENTS_VERIFY_MANUAL,
		PERMISSIONS.PAYMENTS_MANAGE,
		PERMISSIONS.REPORTS_READ,
		PERMISSIONS.REPORTS_EXPORT
	],

	verifier: [
		PERMISSIONS.ADMISSION_PATHS_READ,
		PERMISSIONS.APPLICATIONS_READ,
		PERMISSIONS.APPLICATIONS_VERIFY,
		PERMISSIONS.APPLICATIONS_REJECT,
		PERMISSIONS.SCORES_INPUT,
		PERMISSIONS.SCORES_UPDATE,
		PERMISSIONS.REPORTS_READ
	],

	treasurer: [
		PERMISSIONS.FEES_READ,
		PERMISSIONS.PAYMENTS_READ,
		PERMISSIONS.PAYMENTS_VERIFY_MANUAL,
		PERMISSIONS.PAYMENTS_MANAGE,
		PERMISSIONS.REPORTS_READ,
		PERMISSIONS.REPORTS_EXPORT
	],

	// Epic 4.2: Dedicated interviewer role for scoring
	interviewer: [
		PERMISSIONS.SCORE_CREATE,
		PERMISSIONS.SCORE_READ,
		PERMISSIONS.SCORE_UPDATE,
		PERMISSIONS.SCORE_FINALIZE
	],

	parent: [PERMISSIONS.REPORTS_READ]
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
	const permissions = ROLE_PERMISSIONS[role];
	return permissions.includes(permission);
}

export function getPermissionsForRole(role: UserRole): Permission[] {
	return ROLE_PERMISSIONS[role];
}
